//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.26 at 03:40:23 PM EEST 
//


package org.etsi.uri._02640.v2_;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NamesPostalAddressesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NamesPostalAddressesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NamePostalAddress" type="{http://uri.etsi.org/02640/v2#}NamePostalAddressType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NamesPostalAddressesType", propOrder = {
    "namePostalAddress"
})
public class NamesPostalAddressesType {

    @XmlElement(name = "NamePostalAddress", required = true)
    protected NamePostalAddressType namePostalAddress;

    /**
     * Gets the value of the namePostalAddress property.
     * 
     * @return
     *     possible object is
     *     {@link NamePostalAddressType }
     *     
     */
    public NamePostalAddressType getNamePostalAddress() {
        return namePostalAddress;
    }

    /**
     * Sets the value of the namePostalAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamePostalAddressType }
     *     
     */
    public void setNamePostalAddress(NamePostalAddressType value) {
        this.namePostalAddress = value;
    }

}
