//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.26 at 03:40:23 PM EEST 
//


package org.etsi.uri._02640.v2_;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SenderDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SenderDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NamesPostalAddresses" type="{http://uri.etsi.org/02640/v2#}NamesPostalAddressesType"/>
 *         &lt;element name="AttributedElectronicAddress" type="{http://uri.etsi.org/02640/v2#}AttributedElectronicAddressType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SenderDetailsType", propOrder = {
    "namesPostalAddresses",
    "attributedElectronicAddress"
})
public class SenderDetailsType {

    @XmlElement(name = "NamesPostalAddresses", required = true)
    protected NamesPostalAddressesType namesPostalAddresses;
    @XmlElement(name = "AttributedElectronicAddress", required = true)
    protected AttributedElectronicAddressType attributedElectronicAddress;

    /**
     * Gets the value of the namesPostalAddresses property.
     * 
     * @return
     *     possible object is
     *     {@link NamesPostalAddressesType }
     *     
     */
    public NamesPostalAddressesType getNamesPostalAddresses() {
        return namesPostalAddresses;
    }

    /**
     * Sets the value of the namesPostalAddresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamesPostalAddressesType }
     *     
     */
    public void setNamesPostalAddresses(NamesPostalAddressesType value) {
        this.namesPostalAddresses = value;
    }

    /**
     * Gets the value of the attributedElectronicAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AttributedElectronicAddressType }
     *     
     */
    public AttributedElectronicAddressType getAttributedElectronicAddress() {
        return attributedElectronicAddress;
    }

    /**
     * Sets the value of the attributedElectronicAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributedElectronicAddressType }
     *     
     */
    public void setAttributedElectronicAddress(AttributedElectronicAddressType value) {
        this.attributedElectronicAddress = value;
    }

}
