//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.26 at 03:40:23 PM EEST 
//


package com.modus.edeliveryclient.jaxb.org.etsi.uri._02640.v2_;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SenderMessageDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SenderMessageDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageSubject" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MessageIdentifierByREMMD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isNotification" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SenderMessageDetailsType", propOrder = {
    "messageSubject",
    "messageIdentifierByREMMD"
})
public class SenderMessageDetailsType {

    @XmlElement(name = "MessageSubject", required = true)
    protected String messageSubject;
    @XmlElement(name = "MessageIdentifierByREMMD", required = true)
    protected String messageIdentifierByREMMD;
    @XmlAttribute(name = "isNotification")
    protected String isNotification;

    /**
     * Gets the value of the messageSubject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageSubject() {
        return messageSubject;
    }

    /**
     * Sets the value of the messageSubject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageSubject(String value) {
        this.messageSubject = value;
    }

    /**
     * Gets the value of the messageIdentifierByREMMD property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageIdentifierByREMMD() {
        return messageIdentifierByREMMD;
    }

    /**
     * Sets the value of the messageIdentifierByREMMD property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageIdentifierByREMMD(String value) {
        this.messageIdentifierByREMMD = value;
    }

    /**
     * Gets the value of the isNotification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsNotification() {
        return isNotification;
    }

    /**
     * Sets the value of the isNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsNotification(String value) {
        this.isNotification = value;
    }

}
