//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.26 at 03:40:23 PM EEST 
//


package com.modus.edeliveryclient.jaxb.org.etsi.uri._02640.v2_;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for SubmissionAcceptanceRejectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubmissionAcceptanceRejectionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EventCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EvidenceIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EvidenceIssuerPolicyID" type="{http://uri.etsi.org/02640/v2#}EvidenceIssuerPolicyIDType"/>
 *         &lt;element name="EvidenceIssuerDetails" type="{http://uri.etsi.org/02640/v2#}EvidenceIssuerDetailsType"/>
 *         &lt;element name="SenderAuthenticationDetails" type="{http://uri.etsi.org/02640/v2#}SenderAuthenticationDetailsType"/>
 *         &lt;element name="EventTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="ReplyToAddress" type="{http://uri.etsi.org/02640/v2#}ReplyToAddressType"/>
 *         &lt;element name="SenderDetails" type="{http://uri.etsi.org/02640/v2#}SenderDetailsType"/>
 *         &lt;element name="RecipientsDetails" type="{http://uri.etsi.org/02640/v2#}RecipientsDetailsType"/>
 *         &lt;element name="SenderMessageDetails" type="{http://uri.etsi.org/02640/v2#}SenderMessageDetailsType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubmissionAcceptanceRejectionType", propOrder = {
    "eventCode",
    "evidenceIdentifier",
    "evidenceIssuerPolicyID",
    "evidenceIssuerDetails",
    "senderAuthenticationDetails",
    "eventTime",
    "replyToAddress",
    "senderDetails",
    "recipientsDetails",
    "senderMessageDetails"
})
public class SubmissionAcceptanceRejectionType {

    @XmlElement(name = "EventCode", required = true)
    protected String eventCode;
    @XmlElement(name = "EvidenceIdentifier", required = true)
    protected String evidenceIdentifier;
    @XmlElement(name = "EvidenceIssuerPolicyID", required = true)
    protected EvidenceIssuerPolicyIDType evidenceIssuerPolicyID;
    @XmlElement(name = "EvidenceIssuerDetails", required = true)
    protected EvidenceIssuerDetailsType evidenceIssuerDetails;
    @XmlElement(name = "SenderAuthenticationDetails", required = true)
    protected SenderAuthenticationDetailsType senderAuthenticationDetails;
    @XmlElement(name = "EventTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eventTime;
    @XmlElement(name = "ReplyToAddress", required = true)
    protected ReplyToAddressType replyToAddress;
    @XmlElement(name = "SenderDetails", required = true)
    protected SenderDetailsType senderDetails;
    @XmlElement(name = "RecipientsDetails", required = true)
    protected RecipientsDetailsType recipientsDetails;
    @XmlElement(name = "SenderMessageDetails", required = true)
    protected SenderMessageDetailsType senderMessageDetails;
    @XmlAttribute(name = "Id")
    protected String id;
    @XmlAttribute(name = "version")
    protected String version;

    /**
     * Gets the value of the eventCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventCode() {
        return eventCode;
    }

    /**
     * Sets the value of the eventCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventCode(String value) {
        this.eventCode = value;
    }

    /**
     * Gets the value of the evidenceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvidenceIdentifier() {
        return evidenceIdentifier;
    }

    /**
     * Sets the value of the evidenceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvidenceIdentifier(String value) {
        this.evidenceIdentifier = value;
    }

    /**
     * Gets the value of the evidenceIssuerPolicyID property.
     * 
     * @return
     *     possible object is
     *     {@link EvidenceIssuerPolicyIDType }
     *     
     */
    public EvidenceIssuerPolicyIDType getEvidenceIssuerPolicyID() {
        return evidenceIssuerPolicyID;
    }

    /**
     * Sets the value of the evidenceIssuerPolicyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EvidenceIssuerPolicyIDType }
     *     
     */
    public void setEvidenceIssuerPolicyID(EvidenceIssuerPolicyIDType value) {
        this.evidenceIssuerPolicyID = value;
    }

    /**
     * Gets the value of the evidenceIssuerDetails property.
     * 
     * @return
     *     possible object is
     *     {@link EvidenceIssuerDetailsType }
     *     
     */
    public EvidenceIssuerDetailsType getEvidenceIssuerDetails() {
        return evidenceIssuerDetails;
    }

    /**
     * Sets the value of the evidenceIssuerDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link EvidenceIssuerDetailsType }
     *     
     */
    public void setEvidenceIssuerDetails(EvidenceIssuerDetailsType value) {
        this.evidenceIssuerDetails = value;
    }

    /**
     * Gets the value of the senderAuthenticationDetails property.
     * 
     * @return
     *     possible object is
     *     {@link SenderAuthenticationDetailsType }
     *     
     */
    public SenderAuthenticationDetailsType getSenderAuthenticationDetails() {
        return senderAuthenticationDetails;
    }

    /**
     * Sets the value of the senderAuthenticationDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link SenderAuthenticationDetailsType }
     *     
     */
    public void setSenderAuthenticationDetails(SenderAuthenticationDetailsType value) {
        this.senderAuthenticationDetails = value;
    }

    /**
     * Gets the value of the eventTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEventTime() {
        return eventTime;
    }

    /**
     * Sets the value of the eventTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEventTime(XMLGregorianCalendar value) {
        this.eventTime = value;
    }

    /**
     * Gets the value of the replyToAddress property.
     * 
     * @return
     *     possible object is
     *     {@link ReplyToAddressType }
     *     
     */
    public ReplyToAddressType getReplyToAddress() {
        return replyToAddress;
    }

    /**
     * Sets the value of the replyToAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplyToAddressType }
     *     
     */
    public void setReplyToAddress(ReplyToAddressType value) {
        this.replyToAddress = value;
    }

    /**
     * Gets the value of the senderDetails property.
     * 
     * @return
     *     possible object is
     *     {@link SenderDetailsType }
     *     
     */
    public SenderDetailsType getSenderDetails() {
        return senderDetails;
    }

    /**
     * Sets the value of the senderDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link SenderDetailsType }
     *     
     */
    public void setSenderDetails(SenderDetailsType value) {
        this.senderDetails = value;
    }

    /**
     * Gets the value of the recipientsDetails property.
     * 
     * @return
     *     possible object is
     *     {@link RecipientsDetailsType }
     *     
     */
    public RecipientsDetailsType getRecipientsDetails() {
        return recipientsDetails;
    }

    /**
     * Sets the value of the recipientsDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecipientsDetailsType }
     *     
     */
    public void setRecipientsDetails(RecipientsDetailsType value) {
        this.recipientsDetails = value;
    }

    /**
     * Gets the value of the senderMessageDetails property.
     * 
     * @return
     *     possible object is
     *     {@link SenderMessageDetailsType }
     *     
     */
    public SenderMessageDetailsType getSenderMessageDetails() {
        return senderMessageDetails;
    }

    /**
     * Sets the value of the senderMessageDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link SenderMessageDetailsType }
     *     
     */
    public void setSenderMessageDetails(SenderMessageDetailsType value) {
        this.senderMessageDetails = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
