//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.26 at 03:40:23 PM EEST 
//


package com.modus.edeliveryclient.jaxb.org.etsi.uri._02640.v2_;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.etsi.uri._02640.v2_ package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class V2Factory {

    private final static QName _AttributedElectronicAddress_QNAME = new QName("http://uri.etsi.org/02640/v2#", "AttributedElectronicAddress");
    private final static QName _NamesPostalAddresses_QNAME = new QName("http://uri.etsi.org/02640/v2#", "NamesPostalAddresses");
    private final static QName _SubmissionAcceptanceRejection_QNAME = new QName("http://uri.etsi.org/02640/v2#", "SubmissionAcceptanceRejection");
    private final static QName _EntityNameTypeName_QNAME = new QName("http://uri.etsi.org/02640/v2#", "Name");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.etsi.uri._02640.v2_
     * 
     */
    public V2Factory() {
    }

    /**
     * Create an instance of {@link AttributedElectronicAddressType }
     * 
     */
    public AttributedElectronicAddressType createAttributedElectronicAddressType() {
        return new AttributedElectronicAddressType();
    }

    /**
     * Create an instance of {@link NamesPostalAddressesType }
     * 
     */
    public NamesPostalAddressesType createNamesPostalAddressesType() {
        return new NamesPostalAddressesType();
    }

    /**
     * Create an instance of {@link SubmissionAcceptanceRejectionType }
     * 
     */
    public SubmissionAcceptanceRejectionType createSubmissionAcceptanceRejectionType() {
        return new SubmissionAcceptanceRejectionType();
    }

    /**
     * Create an instance of {@link SenderAuthenticationDetailsType }
     * 
     */
    public SenderAuthenticationDetailsType createSenderAuthenticationDetailsType() {
        return new SenderAuthenticationDetailsType();
    }

    /**
     * Create an instance of {@link ReplyToAddressType }
     * 
     */
    public ReplyToAddressType createReplyToAddressType() {
        return new ReplyToAddressType();
    }

    /**
     * Create an instance of {@link RecipientsDetailsType }
     * 
     */
    public RecipientsDetailsType createRecipientsDetailsType() {
        return new RecipientsDetailsType();
    }

    /**
     * Create an instance of {@link EntityNameType }
     * 
     */
    public EntityNameType createEntityNameType() {
        return new EntityNameType();
    }

    /**
     * Create an instance of {@link EntityDetailsType }
     * 
     */
    public EntityDetailsType createEntityDetailsType() {
        return new EntityDetailsType();
    }

    /**
     * Create an instance of {@link NamePostalAddressType }
     * 
     */
    public NamePostalAddressType createNamePostalAddressType() {
        return new NamePostalAddressType();
    }

    /**
     * Create an instance of {@link PostalAddressType }
     * 
     */
    public PostalAddressType createPostalAddressType() {
        return new PostalAddressType();
    }

    /**
     * Create an instance of {@link EvidenceIssuerDetailsType }
     * 
     */
    public EvidenceIssuerDetailsType createEvidenceIssuerDetailsType() {
        return new EvidenceIssuerDetailsType();
    }

    /**
     * Create an instance of {@link SenderMessageDetailsType }
     * 
     */
    public SenderMessageDetailsType createSenderMessageDetailsType() {
        return new SenderMessageDetailsType();
    }

    /**
     * Create an instance of {@link EvidenceIssuerPolicyIDType }
     * 
     */
    public EvidenceIssuerPolicyIDType createEvidenceIssuerPolicyIDType() {
        return new EvidenceIssuerPolicyIDType();
    }

    /**
     * Create an instance of {@link AdditionalDetailsType }
     * 
     */
    public AdditionalDetailsType createAdditionalDetailsType() {
        return new AdditionalDetailsType();
    }

    /**
     * Create an instance of {@link SenderDetailsType }
     * 
     */
    public SenderDetailsType createSenderDetailsType() {
        return new SenderDetailsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributedElectronicAddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/02640/v2#", name = "AttributedElectronicAddress")
    public JAXBElement<AttributedElectronicAddressType> createAttributedElectronicAddress(AttributedElectronicAddressType value) {
        return new JAXBElement<AttributedElectronicAddressType>(_AttributedElectronicAddress_QNAME, AttributedElectronicAddressType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamesPostalAddressesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/02640/v2#", name = "NamesPostalAddresses")
    public JAXBElement<NamesPostalAddressesType> createNamesPostalAddresses(NamesPostalAddressesType value) {
        return new JAXBElement<NamesPostalAddressesType>(_NamesPostalAddresses_QNAME, NamesPostalAddressesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubmissionAcceptanceRejectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/02640/v2#", name = "SubmissionAcceptanceRejection")
    public JAXBElement<SubmissionAcceptanceRejectionType> createSubmissionAcceptanceRejection(SubmissionAcceptanceRejectionType value) {
        return new JAXBElement<SubmissionAcceptanceRejectionType>(_SubmissionAcceptanceRejection_QNAME, SubmissionAcceptanceRejectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/02640/v2#", name = "Name", scope = EntityNameType.class)
    public JAXBElement<String> createEntityNameTypeName(String value) {
        return new JAXBElement<String>(_EntityNameTypeName_QNAME, String.class, EntityNameType.class, value);
    }

}
